version: '3'

tasks:
  cdk-synth:
    cmds:
      - cdk synth
  cdk-deploy:
    cmds:
      - cdk deploy --require-approval never  
  install-mvn:
    cmds:
      - sudo wget https://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
      - sudo sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
      - sudo yum install -y apache-maven