version: '3'

tasks:
  docker-build-app:
    cmds:
      - docker build -t node-runtime:test .
      - docker run -p 8080:8080
        -e "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" 
        -e "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" 
        -e "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" 
        node-runtime:test
    